export const SET_HARDWARE_DATE = 'SET_HARDWARE_DATE'
export const SET_FUTURE_WEATHER = 'SET_FUTURE_WEATHER'
export const SET_HARDWARE_WEATER = 'SET_HARDWARE_WEATER'
export const SET_HARDWARE_POSITION = 'SET_HARDWARE_POSITION'
